{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goravel-mine.secretName" . }}
  labels:
    {{- include "goravel-mine.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_KEY: {{ required "secret.data.APP_KEY is required when secret.create=true" .Values.secret.data.APP_KEY | quote }}
  JWT_SECRET: {{ required "secret.data.JWT_SECRET is required when secret.create=true" .Values.secret.data.JWT_SECRET | quote }}
  DB_PASSWORD: {{ required "secret.data.DB_PASSWORD is required when secret.create=true" .Values.secret.data.DB_PASSWORD | quote }}
  REDIS_PASSWORD: {{ required "secret.data.REDIS_PASSWORD is required when secret.create=true" .Values.secret.data.REDIS_PASSWORD | quote }}
{{ if eq (toString (index .Values.app.env "OBS_METRICS_ENABLED")) "true" }}
  OBS_METRICS_TOKEN: {{ required "secret.data.OBS_METRICS_TOKEN is required when OBS_METRICS_ENABLED=true and secret.create=true" .Values.secret.data.OBS_METRICS_TOKEN | quote }}
{{ else }}
  OBS_METRICS_TOKEN: {{ .Values.secret.data.OBS_METRICS_TOKEN | quote }}
{{ end }}
{{- end }}
