export interface MineModuleManifest {
  id: string
  apiFiles: string[]
  views: string[]
  locales: string[]
  menus: Array<{
    key: string
    title: string
    path: string
    component: string
    permission: string
  }>
  permissions: Array<{
    key: string
    title: string
  }>
}

export const baseModuleManifest = {
  id: 'base',
  apiFiles: [
    'src/modules/base/api/attachment.ts',
    'src/modules/base/api/department.ts',
    'src/modules/base/api/dictionary.ts',
    'src/modules/base/api/leader.ts',
    'src/modules/base/api/log.ts',
    'src/modules/base/api/menu.ts',
    'src/modules/base/api/permission.ts',
    'src/modules/base/api/platformDictionary.ts',
    'src/modules/base/api/platformMenu.ts',
    'src/modules/base/api/platformMiddleware.ts',
    'src/modules/base/api/platformModuleLifecycle.ts',
    'src/modules/base/api/platformObservability.ts',
    'src/modules/base/api/platformReferenceCase.ts',
    'src/modules/base/api/platformRole.ts',
    'src/modules/base/api/platformScheduledTask.ts',
    'src/modules/base/api/platformStorageConfig.ts',
    'src/modules/base/api/platformTenantPlan.ts',
    'src/modules/base/api/platformUser.ts',
    'src/modules/base/api/position.ts',
    'src/modules/base/api/role.ts',
    'src/modules/base/api/ssoLoginLog.ts',
    'src/modules/base/api/ssoProvider.ts',
    'src/modules/base/api/ssoUserBinding.ts',
    'src/modules/base/api/tenant.ts',
    'src/modules/base/api/user.ts',
  ],
  views: [
    'src/modules/base/views/dataCenter/attachment/index.vue',
    'src/modules/base/views/dataCenter/dictionary/form.vue',
    'src/modules/base/views/dataCenter/dictionary/index.vue',
    'src/modules/base/views/log/ssoLogin.vue',
    'src/modules/base/views/log/userLogin.vue',
    'src/modules/base/views/log/userOperation.vue',
    'src/modules/base/views/permission/department/form.vue',
    'src/modules/base/views/permission/department/index.vue',
    'src/modules/base/views/permission/department/position.vue',
    'src/modules/base/views/permission/department/setLeader.vue',
    'src/modules/base/views/permission/menu/index.vue',
    'src/modules/base/views/permission/role/form.vue',
    'src/modules/base/views/permission/role/index.vue',
    'src/modules/base/views/permission/user/form.vue',
    'src/modules/base/views/permission/user/index.vue',
    'src/modules/base/views/platform/dictionary/form.vue',
    'src/modules/base/views/platform/dictionary/index.vue',
    'src/modules/base/views/platform/menu/index.vue',
    'src/modules/base/views/platform/middleware/components/AdapterTab.vue',
    'src/modules/base/views/platform/middleware/components/DeadLetterTab.vue',
    'src/modules/base/views/platform/middleware/components/DeliveryTab.vue',
    'src/modules/base/views/platform/middleware/components/MetricsTab.vue',
    'src/modules/base/views/platform/middleware/components/ProtectionTab.vue',
    'src/modules/base/views/platform/middleware/components/RouteTab.vue',
    'src/modules/base/views/platform/middleware/index.vue',
    'src/modules/base/views/platform/moduleLifecycle/index.vue',
    'src/modules/base/views/platform/observability/index.vue',
    'src/modules/base/views/platform/referenceCase/index.vue',
    'src/modules/base/views/platform/role/form.vue',
    'src/modules/base/views/platform/role/index.vue',
    'src/modules/base/views/platform/scheduledTask/form.vue',
    'src/modules/base/views/platform/scheduledTask/index.vue',
    'src/modules/base/views/platform/storageConfig/form.vue',
    'src/modules/base/views/platform/storageConfig/index.vue',
    'src/modules/base/views/platform/tenant/form.vue',
    'src/modules/base/views/platform/tenant/index.vue',
    'src/modules/base/views/platform/tenantPlan/form.vue',
    'src/modules/base/views/platform/tenantPlan/index.vue',
    'src/modules/base/views/platform/user/form.vue',
    'src/modules/base/views/platform/user/index.vue',
    'src/modules/base/views/security/ssoProvider/form.vue',
    'src/modules/base/views/security/ssoProvider/index.vue',
    'src/modules/base/views/security/ssoUserBinding/index.vue',
  ],
  locales: [
    'src/modules/base/locales/en[English].yaml',
    'src/modules/base/locales/zh_CN[简体中文].yaml',
    'src/modules/base/locales/zh_TW[繁體中文].yaml',
  ],
  menus: [
    { key: 'platform:tenant', title: '租户管理', path: '/tenant-manage/tenant', component: 'base/views/platform/tenant/index', permission: 'platform:tenant:list' },
    { key: 'platform:tenantPlan', title: '套餐管理', path: '/tenant-manage/tenant-plan', component: 'base/views/platform/tenantPlan/index', permission: 'platform:tenantPlan:list' },
    { key: 'platform:user', title: '平台用户', path: '/platform/user', component: 'base/views/platform/user/index', permission: 'platform:user:list' },
    { key: 'platform:role', title: '平台角色', path: '/platform/role', component: 'base/views/platform/role/index', permission: 'platform:role:list' },
    { key: 'platform:menu', title: '平台菜单', path: '/platform/menu', component: 'base/views/platform/menu/index', permission: 'platform:menu:list' },
    { key: 'platform:dictionary', title: '字典管理', path: '/platform-system/dictionary', component: 'base/views/platform/dictionary/index', permission: 'platform:dictionary:list' },
    { key: 'platform:storageConfig', title: '储存配置', path: '/platform-system/storage-config', component: 'base/views/platform/storageConfig/index', permission: 'platform:storageConfig:list' },
    { key: 'platform:scheduledTask', title: '计划任务', path: '/platform-system/scheduled-task', component: 'base/views/platform/scheduledTask/index', permission: 'platform:scheduledTask:list' },
    { key: 'platform:middleware', title: '中间件平台', path: '/platform-system/middleware', component: 'base/views/platform/middleware/index', permission: 'platform:middleware:list' },
    { key: 'platform:moduleLifecycle', title: '模块治理', path: '/platform-system/module-lifecycle', component: 'base/views/platform/moduleLifecycle/index', permission: 'platform:moduleLifecycle:list' },
    { key: 'platform:referenceCase', title: '参考模块', path: '/platform-system/reference-case', component: 'base/views/platform/referenceCase/index', permission: 'platform:referenceCase:list' },
    { key: 'platform:observability', title: '系统监控', path: '/dashboard/observability', component: 'base/views/platform/observability/index', permission: 'platform:observability:list' },
    { key: 'permission:user', title: '用户管理', path: '/permission/user', component: 'base/views/permission/user/index', permission: 'permission:user:index' },
    { key: 'permission:menu', title: '菜单管理', path: '/permission/menu', component: 'base/views/permission/menu/index', permission: 'permission:menu:index' },
    { key: 'permission:role', title: '角色管理', path: '/permission/role', component: 'base/views/permission/role/index', permission: 'permission:role:index' },
    { key: 'permission:department', title: '部门管理', path: '/permission/department', component: 'base/views/permission/department/index', permission: 'permission:department:index' },
    { key: 'permission:position', title: '岗位管理', path: '/permission/position', component: 'base/views/permission/department/index', permission: 'permission:position:index' },
    { key: 'permission:leader', title: '领导管理', path: '/permission/leader', component: 'base/views/permission/department/index', permission: 'permission:leader:index' },
    { key: 'dataCenter:dictionary', title: '数据字典', path: '/data-center/dictionary', component: 'base/views/dataCenter/dictionary/index', permission: 'dataCenter:dictionary:list' },
    { key: 'dataCenter:attachment', title: '附件管理', path: '/data-center/attachment', component: 'base/views/dataCenter/attachment/index', permission: 'dataCenter:attachment:list' },
    { key: 'security:ssoProvider', title: '身份源配置', path: '/security/sso/provider', component: 'base/views/security/ssoProvider/index', permission: 'security:ssoProvider:list' },
    { key: 'security:ssoUserBinding', title: '用户绑定', path: '/security/sso/binding', component: 'base/views/security/ssoUserBinding/index', permission: 'security:ssoUserBinding:list' },
    { key: 'security:ssoLoginAudit', title: '登录审计', path: '/security/sso/login-audit', component: 'base/views/log/ssoLogin', permission: 'log:ssoLogin:list' },
    { key: 'log:userLogin', title: '登录日志', path: '/log/user-login', component: 'base/views/log/userLogin', permission: 'log:userLogin:list' },
    { key: 'log:userOperation', title: '操作日志', path: '/log/user-operation', component: 'base/views/log/userOperation', permission: 'log:userOperation:list' },
  ],
  permissions: [
    { key: 'platform:tenant:list', title: '租户列表' },
    { key: 'platform:tenant:save', title: '租户保存' },
    { key: 'platform:tenant:update', title: '租户更新' },
    { key: 'platform:tenant:suspend', title: '租户挂起' },
    { key: 'platform:tenant:resume', title: '租户恢复' },
    { key: 'platform:tenant:archive', title: '租户归档' },
    { key: 'platform:tenant:destroy', title: '租户销毁' },
    { key: 'platform:tenant:usage', title: '租户用量' },
    { key: 'platform:tenant:governance', title: '租户治理' },
    { key: 'platform:tenant:export', title: '租户数据导出' },
    { key: 'platform:tenant:permissions', title: '租户权限分配' },
    { key: 'platform:tenant:updatePlan', title: '租户套餐变更' },
    { key: 'platform:tenantPlan:list', title: '套餐列表' },
    { key: 'platform:tenantPlan:save', title: '套餐保存' },
    { key: 'platform:tenantPlan:update', title: '套餐更新' },
    { key: 'platform:tenantPlan:delete', title: '套餐删除' },
    { key: 'platform:user:list', title: '平台用户列表' },
    { key: 'platform:user:save', title: '平台用户保存' },
    { key: 'platform:user:update', title: '平台用户更新' },
    { key: 'platform:user:delete', title: '平台用户删除' },
    { key: 'platform:user:password', title: '平台用户初始化密码' },
    { key: 'platform:user:getRole', title: '获取平台用户角色' },
    { key: 'platform:user:setRole', title: '平台用户角色赋予' },
    { key: 'platform:role:list', title: '平台角色列表' },
    { key: 'platform:role:save', title: '平台角色保存' },
    { key: 'platform:role:update', title: '平台角色更新' },
    { key: 'platform:role:delete', title: '平台角色删除' },
    { key: 'platform:role:getMenu', title: '获取平台角色菜单' },
    { key: 'platform:role:setMenu', title: '平台角色菜单赋予' },
    { key: 'platform:menu:list', title: '平台菜单列表' },
    { key: 'platform:menu:create', title: '平台菜单保存' },
    { key: 'platform:menu:save', title: '平台菜单更新' },
    { key: 'platform:menu:delete', title: '平台菜单删除' },
    { key: 'platform:dictionary:list', title: '字典列表' },
    { key: 'platform:dictionary:save', title: '字典保存' },
    { key: 'platform:dictionary:update', title: '字典更新' },
    { key: 'platform:dictionary:delete', title: '字典删除' },
    { key: 'platform:dictionary:dispatch', title: '字典分发' },
    { key: 'platform:storageConfig:list', title: '储存配置列表' },
    { key: 'platform:storageConfig:save', title: '储存配置保存' },
    { key: 'platform:storageConfig:update', title: '储存配置更新' },
    { key: 'platform:storageConfig:delete', title: '储存配置删除' },
    { key: 'platform:attachment:upload', title: '平台附件上传' },
    { key: 'platform:scheduledTask:list', title: '计划任务列表' },
    { key: 'platform:scheduledTask:save', title: '计划任务保存' },
    { key: 'platform:scheduledTask:update', title: '计划任务更新' },
    { key: 'platform:scheduledTask:delete', title: '计划任务删除' },
    { key: 'platform:scheduledTask:run', title: '计划任务执行' },
    { key: 'platform:scheduledTask:log', title: '计划任务日志' },
    { key: 'platform:middleware:list', title: '中间件平台查看' },
    { key: 'platform:middleware:configure', title: '中间件平台配置' },
    { key: 'platform:middleware:execute', title: '中间件平台执行' },
    { key: 'platform:middleware:publish', title: '中间件发布' },
    { key: 'platform:middleware:replay', title: '消息死信重放' },
    { key: 'platform:middleware:payload', title: '消息载荷查看' },
    { key: 'platform:queueFailedJob:list', title: '失败队列列表' },
    { key: 'platform:queueFailedJob:retry', title: '失败队列重试' },
    { key: 'platform:queueFailedJob:delete', title: '失败队列丢弃' },
    { key: 'platform:observability:list', title: '监控面板' },
    { key: 'platform:moduleLifecycle:list', title: '模块治理面板' },
    { key: 'platform:moduleLifecycle:execute', title: '模块生命周期执行' },
    { key: 'platform:moduleLifecycle:log', title: '模块生命周期日志' },
    { key: 'platform:referenceCase:list', title: '参考模块列表' },
    { key: 'platform:referenceCase:save', title: '参考模块保存' },
    { key: 'platform:referenceCase:update', title: '参考模块更新' },
    { key: 'platform:referenceCase:delete', title: '参考模块删除' },
    { key: 'platform:security:mfa', title: '平台 MFA 管理' },
    { key: 'platform:security:control', title: '平台安全控制' },
    { key: 'permission:user:index', title: '用户列表' },
    { key: 'permission:user:save', title: '用户保存' },
    { key: 'permission:user:update', title: '用户更新' },
    { key: 'permission:user:delete', title: '用户删除' },
    { key: 'permission:user:password', title: '用户初始化密码' },
    { key: 'permission:user:getRole', title: '获取用户角色' },
    { key: 'permission:user:setRole', title: '用户角色赋予' },
    { key: 'permission:menu:index', title: '菜单列表' },
    { key: 'permission:menu:create', title: '菜单保存' },
    { key: 'permission:menu:save', title: '菜单更新' },
    { key: 'permission:menu:delete', title: '菜单删除' },
    { key: 'permission:role:index', title: '角色列表' },
    { key: 'permission:role:save', title: '角色保存' },
    { key: 'permission:role:update', title: '角色更新' },
    { key: 'permission:role:delete', title: '角色删除' },
    { key: 'permission:role:getMenu', title: '获取角色菜单' },
    { key: 'permission:role:setMenu', title: '角色菜单赋予' },
    { key: 'permission:department:index', title: '部门列表' },
    { key: 'permission:department:save', title: '部门保存' },
    { key: 'permission:department:update', title: '部门更新' },
    { key: 'permission:department:delete', title: '部门删除' },
    { key: 'permission:position:index', title: '岗位列表' },
    { key: 'permission:position:save', title: '岗位保存' },
    { key: 'permission:position:update', title: '岗位更新' },
    { key: 'permission:position:delete', title: '岗位删除' },
    { key: 'permission:position:data_permission', title: '岗位数据权限' },
    { key: 'permission:leader:index', title: '领导列表' },
    { key: 'permission:leader:save', title: '领导保存' },
    { key: 'permission:leader:delete', title: '领导删除' },
    { key: 'dataCenter:dictionary:list', title: '数据字典列表' },
    { key: 'dataCenter:dictionary:update', title: '数据字典更新' },
    { key: 'dataCenter:attachment:list', title: '附件列表' },
    { key: 'dataCenter:attachment:upload', title: '附件上传' },
    { key: 'dataCenter:attachment:delete', title: '附件删除' },
    { key: 'security:mfa', title: '租户 MFA 管理' },
    { key: 'security:ssoProvider:list', title: '单点登录配置列表' },
    { key: 'security:ssoProvider:save', title: '单点登录配置保存' },
    { key: 'security:ssoProvider:update', title: '单点登录配置更新' },
    { key: 'security:ssoProvider:delete', title: '单点登录配置删除' },
    { key: 'security:ssoUserBinding:list', title: '单点登录用户绑定列表' },
    { key: 'security:ssoUserBinding:detail', title: '单点登录用户绑定详情' },
    { key: 'security:ssoUserBinding:user', title: '用户单点登录绑定' },
    { key: 'security:ssoUserBinding:unbind', title: '单点登录解绑' },
    { key: 'log:ssoLogin:list', title: 'SSO 登录日志列表' },
    { key: 'log:ssoLogin:stats', title: 'SSO 登录统计' },
    { key: 'log:userLogin:list', title: '登录日志列表' },
    { key: 'log:userOperation:list', title: '操作日志列表' },
  ],
} as const satisfies MineModuleManifest

export default baseModuleManifest
