apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: goravel-mine
  namespace: goravel-mine
  labels:
    app.kubernetes.io/name: goravel-mine
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: goravel-mine
  namespaceSelector:
    matchNames:
      - goravel-mine
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scheme: http
      authorization:
        type: Bearer
        credentials:
          name: goravel-mine-secret
          key: OBS_METRICS_TOKEN
