import fs from 'node:fs'
import path from 'node:path'
import process from 'node:process'
import ts from 'typescript'

interface JsonSchema {
  $ref?: string
  type?: string | string[]
  enum?: unknown[]
  const?: unknown
  required?: string[]
  properties?: Record<string, JsonSchema>
  additionalProperties?: boolean | JsonSchema
  items?: JsonSchema
  allOf?: JsonSchema[]
  oneOf?: JsonSchema[]
  anyOf?: JsonSchema[]
  format?: string
}

interface OpenAPIOperation {
  operationId?: string
  parameters?: OpenAPIParameter[]
  requestBody?: OpenAPIRequestBody
  responses?: Record<string, OpenAPIResponse>
}

type OpenAPIParameter = OpenAPIRef | {
  name?: string
  in?: string
  required?: boolean
  schema?: JsonSchema
}

type OpenAPIRequestBody = OpenAPIRef | {
  content?: Record<string, { schema?: JsonSchema }>
}

type OpenAPIResponse = OpenAPIRef | {
  content?: Record<string, { schema?: JsonSchema }>
}

interface OpenAPIRef {
  $ref: string
}

interface OpenAPISpec {
  paths: Record<string, Record<string, OpenAPIOperation>>
  components?: {
    schemas?: Record<string, JsonSchema>
    parameters?: Record<string, OpenAPIParameter>
    requestBodies?: Record<string, OpenAPIOperation['requestBody']>
    responses?: Record<string, OpenAPIOperation['responses'][string]>
  }
}

const repoRoot = path.resolve(process.cwd(), '..')
const specPath = path.join(repoRoot, 'docs/api-contract/openapi/admin-base-apis.openapi.json')
const outputFile = path.join(process.cwd(), 'src/generated/admin-api.ts')
const declarationDir = path.join(process.cwd(), 'tmp/sdk/admin-api')
const declarationFile = path.join(declarationDir, 'admin-api.d.ts')
const mode = process.argv.includes('--write') ? 'write' : 'check'
const spec = JSON.parse(fs.readFileSync(specPath, 'utf8')) as OpenAPISpec

const sdkContent = renderSdk(spec)
if (mode === 'write') {
  fs.mkdirSync(path.dirname(outputFile), { recursive: true })
  fs.writeFileSync(outputFile, sdkContent)
}
else {
  const current = fs.existsSync(outputFile) ? fs.readFileSync(outputFile, 'utf8') : ''
  if (current !== sdkContent) {
    throw new Error(`generated OpenAPI SDK is out of date: ${path.relative(process.cwd(), outputFile)}`)
  }
}

const configPath = ts.findConfigFile(process.cwd(), ts.sys.fileExists, 'tsconfig.json')
if (!configPath) {
  throw new Error('tsconfig.json not found')
}

const configFile = ts.readConfigFile(configPath, ts.sys.readFile)
if (configFile.error) {
  throw new Error(formatDiagnostics([configFile.error]))
}

const parsedConfig = ts.parseJsonConfigFileContent(configFile.config, ts.sys, process.cwd(), {
  declaration: true,
  emitDeclarationOnly: true,
  noEmit: false,
  outDir: declarationDir,
}, configPath, undefined, [{ extension: 'mts', isMixedContent: false, scriptKind: ts.ScriptKind.TS }])

fs.rmSync(declarationDir, { recursive: true, force: true })
fs.mkdirSync(declarationDir, { recursive: true })

const program = ts.createProgram([outputFile], parsedConfig.options)
const emit = program.emit()
const diagnostics = ts.getPreEmitDiagnostics(program).concat(emit.diagnostics)
if (diagnostics.length > 0) {
  throw new Error(formatDiagnostics(diagnostics))
}
if (!fs.existsSync(declarationFile)) {
  throw new Error(`SDK declaration was not emitted: ${declarationFile}`)
}

console.log(`OpenAPI SDK contract OK: ${path.relative(process.cwd(), outputFile)}`)

function renderSdk(api: OpenAPISpec): string {
  const schemaNames = Object.keys(api.components?.schemas ?? {}).sort()
  const operations = collectOperations(api)

  return [
    '/* eslint-disable */',
    '// Generated by scripts/check-openapi-sdk.mts. Do not edit.',
    ...schemaNames.map(name => `export type ${safeTypeName(name)} = ${schemaToType(api.components?.schemas?.[name] ?? {}, api)}`),
    'export type HttpMethod = \'delete\' | \'get\' | \'patch\' | \'post\' | \'put\'',
    'export type ApiOperation<Request = unknown, Response = unknown, Params = Record<string, never>> = { method: HttpMethod, path: string, request: Request, response: Response, params: Params }',
    'export type OperationRequest<Name extends keyof Operations> = Operations[Name][\'request\']',
    'export type OperationResponse<Name extends keyof Operations> = Operations[Name][\'response\']',
    'export type OperationParams<Name extends keyof Operations> = Operations[Name][\'params\']',
    'export interface Operations {',
    ...operations.map(operation => `  ${operation.operationId}: ApiOperation<${operation.requestType}, ${operation.responseType}, ${operation.paramsType}>`),
    '}',
    'export const operations = {',
    ...operations.map(operation => `  ${operation.operationId}: { method: '${operation.method}', path: '${operation.path}' },`),
    '} as const',
    '',
  ].join('\n')
}

function collectOperations(api: OpenAPISpec) {
  return Object.entries(api.paths)
    .flatMap(([apiPath, methods]) => Object.entries(methods).map(([method, operation]) => {
      if (!operation.operationId) {
        throw new Error(`${method.toUpperCase()} ${apiPath} missing operationId`)
      }
      return {
        method,
        path: apiPath,
        operationId: safePropertyName(operation.operationId),
        paramsType: parametersToType(operation.parameters ?? [], api),
        requestType: requestBodyToType(operation.requestBody, api),
        responseType: responseToType(operation.responses?.['200'], api),
      }
    }))
    .sort((left, right) => left.operationId.localeCompare(right.operationId))
}

function schemaToType(schema: JsonSchema | undefined, api: OpenAPISpec): string {
  if (!schema) {
    return 'unknown'
  }
  if (schema.$ref) {
    return safeTypeName(refName(schema.$ref))
  }
  if (schema.const !== undefined) {
    return literalType(schema.const)
  }
  if (schema.enum) {
    return schema.enum.map(literalType).join(' | ') || 'never'
  }
  if (schema.oneOf?.length) {
    return schema.oneOf.map(child => schemaToType(child, api)).join(' | ')
  }
  if (schema.anyOf?.length) {
    return schema.anyOf.map(child => schemaToType(child, api)).join(' | ')
  }
  if (schema.allOf?.length) {
    return schema.allOf.map(child => schemaToType(child, api)).join(' & ')
  }

  const type = Array.isArray(schema.type) ? schema.type.filter(item => item !== 'null')[0] : schema.type
  if (Array.isArray(schema.type) && schema.type.includes('null')) {
    return `${schemaToType({ ...schema, type }, api)} | null`
  }

  switch (type) {
    case 'array':
      return `${schemaToType(schema.items, api)}[]`
    case 'boolean':
      return 'boolean'
    case 'integer':
    case 'number':
      return 'number'
    case 'object':
      return objectToType(schema, api)
    case 'string':
      return schema.format === 'binary' ? 'Blob | File' : 'string'
    default:
      if (schema.properties) {
        return objectToType(schema, api)
      }
      return 'unknown'
  }
}

function objectToType(schema: JsonSchema, api: OpenAPISpec): string {
  const properties = Object.entries(schema.properties ?? {})
  const required = new Set(schema.required ?? [])
  const fields = properties.map(([name, value]) => {
    const suffix = required.has(name) ? '' : '?'
    return `${JSON.stringify(name)}${suffix}: ${schemaToType(value, api)}`
  })

  if (schema.additionalProperties) {
    const valueType = typeof schema.additionalProperties === 'object'
      ? schemaToType(schema.additionalProperties, api)
      : 'unknown'
    fields.push(`[key: string]: ${valueType}`)
  }

  return fields.length > 0 ? `{ ${fields.join('; ')} }` : 'Record<string, never>'
}

function parametersToType(parameters: OpenAPIParameter[], api: OpenAPISpec): string {
  const fields = parameters.map((parameter) => {
    const resolved = resolveParameter(parameter, api)
    if (!resolved.name) {
      throw new Error(`parameter missing name: ${JSON.stringify(parameter)}`)
    }
    const suffix = resolved.required ? '' : '?'
    return `${JSON.stringify(resolved.name)}${suffix}: ${schemaToType(resolved.schema, api)}`
  })
  return fields.length > 0 ? `{ ${fields.join('; ')} }` : 'Record<string, never>'
}

function requestBodyToType(requestBody: OpenAPIOperation['requestBody'], api: OpenAPISpec): string {
  if (!requestBody) {
    return 'void'
  }
  const resolved = resolveRequestBody(requestBody, api)
  const schema = resolved?.content?.['application/json']?.schema
    ?? resolved?.content?.['multipart/form-data']?.schema
  return schemaToType(schema, api)
}

function responseToType(response: OpenAPIOperation['responses'][string] | undefined, api: OpenAPISpec): string {
  if (!response) {
    return 'unknown'
  }
  const resolved = resolveResponse(response, api)
  return schemaToType(resolved?.content?.['application/json']?.schema, api)
}

function resolveParameter(parameter: OpenAPIParameter, api: OpenAPISpec): OpenAPIParameterValue {
  if (isRef(parameter)) {
    const resolved = api.components?.parameters?.[refName(parameter.$ref)]
    if (!resolved || isRef(resolved)) {
      throw new Error(`unresolved parameter ref: ${parameter.$ref}`)
    }
    return resolved
  }
  return parameter
}

function resolveRequestBody(requestBody: OpenAPIRequestBody, api: OpenAPISpec): OpenAPIRequestBodyValue {
  if (isRef(requestBody)) {
    const resolved = api.components?.requestBodies?.[refName(requestBody.$ref)]
    if (!resolved || isRef(resolved)) {
      throw new Error(`unresolved requestBody ref: ${requestBody.$ref}`)
    }
    return resolved
  }
  return requestBody
}

function resolveResponse(response: OpenAPIResponse, api: OpenAPISpec): OpenAPIResponseValue {
  if (isRef(response)) {
    const resolved = api.components?.responses?.[refName(response.$ref)]
    if (!resolved || isRef(resolved)) {
      throw new Error(`unresolved response ref: ${response.$ref}`)
    }
    return resolved
  }
  return response
}

type OpenAPIParameterValue = Exclude<OpenAPIParameter, OpenAPIRef>
type OpenAPIRequestBodyValue = Exclude<OpenAPIRequestBody, OpenAPIRef>
type OpenAPIResponseValue = Exclude<OpenAPIResponse, OpenAPIRef>

function isRef(value: unknown): value is OpenAPIRef {
  return Boolean(value && typeof value === 'object' && '$ref' in value)
}

function refName(ref: string): string {
  return ref.slice(ref.lastIndexOf('/') + 1)
}

function safeTypeName(name: string): string {
  return name.replace(/[^\w$]/g, '_').replace(/^([^A-Z_$])/i, '_$1')
}

function safePropertyName(name: string): string {
  return /^[A-Z_$][\w$]*$/i.test(name) ? name : JSON.stringify(name)
}

function literalType(value: unknown): string {
  return typeof value === 'string' ? JSON.stringify(value) : String(value)
}

function formatDiagnostics(diagnostics: readonly ts.Diagnostic[]): string {
  return ts.formatDiagnosticsWithColorAndContext(diagnostics, {
    getCanonicalFileName: fileName => fileName,
    getCurrentDirectory: process.cwd,
    getNewLine: () => '\n',
  })
}
